services:
  nginx:
    image: nginx:latest
    container_name: syslog-web
    ports:
      - "8080:80"
    volumes:
      - ./reports_web:/var/www/html/daily_logs
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./html:/usr/share/nginx/html:ro
