services:
  nginx:
    image: nginx:latest
    container_name: syslog-web
    ports:
      - "8080:80"
    volumes:
      - /opt/system_reports:/usr/share/nginx/html/daily_logs
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - .html:/usr/share/nginx/html:ro
