services:
  nginx:
    image: nginx:latest
    container_name: syslog-web
    ports:
      - "8080:80"
    volumes:
#      - ./html:/var/www/html/daily_logs
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./html:/var/www/html:ro
