---

- name: Update Packages
  apt:
    upgrade: yes
    update_cache: yes

- name: Configure current DHCP address as a static IP -> Debian
  ansible.builtin.template:
    src: files/interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'

- name: Add primary user to the Sudo Group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: sudo
    append: yes
  become: true
  notify: reboot server
